In [ ]:
Numpy - são martrizes
ocupa menos memória do computador
amplamente utilizado na análise de dados
serve para modelagens, processamento de imagens

1. Instalando o Numpy



In [2]:
pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/82/0f/3f712cd84371636c5375d2dd70e7514d264cec6bdfc3d7997a4236e9f948/numpy-1.26.1-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.2 kB 217.9 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 375.8 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 361.4 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.2/15.8 MB 5.9 MB/s eta 0:00:03
   - -------------------------------------- 0.4/15.8 MB 5.1 MB/s eta 0:00:04
   - -------------------------------------- 0.7/15.8 MB 5.5 MB/s eta 0:00:03
   -- ------------------------------------- 0.9/15.8 MB 5.7 MB/s eta 0:00:03
   --- -------------------------


[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np


In [4]:
# Criando arrays unidimensionais
arr_str = np.array(['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Campo Grande', 'Vitória', 'Curitiba'])
arr_float = np.array([0.3, 13.9, 29.6, -109.2, 98.4, 0.0087])
arr_int = np.array([0, 10,  20, 30, 40, 50])
arr_bool = np.array([False, True, True, False, True, True])

print(arr_str)
print(arr_float)
print(arr_int)
print(arr_bool)

['São Paulo' 'Rio de Janeiro' 'Belo Horizonte' 'Campo Grande' 'Vitória'
 'Curitiba']
[ 3.000e-01  1.390e+01  2.960e+01 -1.092e+02  9.840e+01  8.700e-03]
[ 0 10 20 30 40 50]
[False  True  True False  True  True]


In [5]:
# verificando a estrutura dos arrays
print(type(arr_str))
print(type(arr_float))
print(type(arr_int))
print(type(arr_bool))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
# criando um array com estrutura heterogênea
arr_varios = np.array(['FEA.dev', 0.3, 0, False])
arr_varios

array(['FEA.dev', '0.3', '0', 'False'], dtype='<U32')

In [8]:
# operacoes matemáticas
arr_int += 1
arr_int

array([ 2, 12, 22, 32, 42, 52])

In [9]:
arr_varios += 1

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U32'), dtype('int32')) -> None

Array vs Lista

ambos armazenam dados, são mutáveis
lista armazena dados heterogêneos enquanto array é homogêneo e instalado
pq array?
maior flexibilidade nos calculos matematicos
mais velocidade
menor armanezamento

exemplo: media ponderada n1p1 + n2p2 + nnpn / n1 + n2 + nn



In [11]:
notas = [2.0, 5.0, 9.0, 3.0, 7.0]
pesos = [2, 1, 2, 5, 5]


In [13]:
#a lista não permite fazer assim: (notas * pesos) / pesos - vai  dar erros
#se somar notas + pesos vai concatenar as 2 listas em 1 só


In [16]:
#Metodo para calcular a média ponderada utilizando listas: list comprehension
nota_final = sum(nota * peso for nota, peso in zip(notas,pesos)) / sum(pesos)
print(nota_final)

5.133333333333334


In [18]:
#Calculando as medias ponderadas utilizando o Numpy
##Convertendo as listas com notas em numpy arrays
notas_array = np.array(notas)
pesos_array = np.array(pesos)

print(notas_array, pesos_array)

[2. 5. 9. 3. 7.] [2 1 2 5 5]


In [20]:
#Cálculo da nota final utilizando o Numpy
(sum(notas_array*pesos_array))/sum(pesos_array)

5.133333333333334

In [22]:
# É possivel realizar qualquer operação com numpy array, como soma
notas_array + 1

array([ 3.,  6., 10.,  4.,  8.])

In [24]:
#Subtração
notas_array -1

array([1., 4., 8., 2., 6.])

C R I A N D O  A R R A Y S  C O M  N U M P Y !!!!

In [7]:
#preenchida com zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
#Array vazio 
np.empty(3)

array([0., 0., 0.])

In [33]:
# Array sequencial, comeca em zero e exclui o ultimo valor
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
#sequencial com inntervalos uniformemente espaçados
np.arange(0, 20, 5)

array([ 0,  5, 10, 15])

In [37]:
#sequencial com valores que são espaçados linearmente em um intervalo especificado
np.linspace(0, 22, num = 5)

array([ 0. ,  5.5, 11. , 16.5, 22. ])

In [39]:
#Array com valores aleatórios entre 0 e 1
# 2 linhas e 4 colunas
np.random.random((2,4))

array([[0.0038423 , 0.23195011, 0.06011911, 0.96803651],
       [0.79107051, 0.53656184, 0.73610239, 0.41357417]])

In [9]:
# Matriz Identidade
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [43]:
#Manipular Numpy Arrays
#considere estes dois numpy arrays
a =  np.array([5, 4, 3, 2, 1])
b = np.array([10,  9, 8, 7, 6])

In [45]:
#Unir os dois arrays
c = np.concatenate((a,b))
c

array([ 5,  4,  3,  2,  1, 10,  9,  8,  7,  6])

In [47]:
#Colocar em ordem crescente
c_crescente = np.sort(c)
c_crescente

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
#Filtrar os elementos divisíveis por 2
c_crescente[c_crescente % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [51]:
#filtrar os elementos divisiveis por 2 e por 5
c_crescente[(c_crescente % 2 == 0) & (c_crescente % 5 == 0)]

array([10])

In [53]:
#substituir elementos que não são divisiveis por 3 e pelo numero 0
#aonde o resto da div por 3 for zero ele vai manter, no resto vai substituir por 0
np.where(c_crescente % 3 == 0, c_crescente, 0)

array([0, 0, 3, 0, 0, 6, 0, 0, 9, 0])

In [2]:
import time #medir eificiência

In [5]:
#Criar um array aleatória com 1 bilhão de elementos entre R$ 0 e R$ 1000
#Esse array representa preço de fechamento de um portfólio de ativos da FEA.dev
start_time = time.time()

ativos_dev = np.random.randint(0,1001, size = 1_000_000_000)

end_time = time.time()
print(f'Result calculated in {(end_time - start_time)//60} minutes and {(end_time - start_time)%60} seconds')

Result calculated in 0.0 minutes and 12.047314882278442 seconds


In [6]:
#verificar se realmente há um bilhao de elementos
len(ativos_dev)

1000000000

In [7]:
from random import randint
lista_teste = []
for i in range(1_000_000_000):
    lista_teste.append(randint(0,1001))

#esperei quase 13 minutos e ainda não tinha acabado!!!!!!

MemoryError: 

In [8]:
#verificar se realmente há um bilhão de elementos no array criado (shape)
ativos_dev.shape

(1000000000,)

In [13]:
#encontrar o valor mínimo do array
ativos_dev.min()

0

In [14]:
#encontrar o valor máximo do array
ativos_dev.max()

1000

In [15]:
#encontrar a soma do array
ativos_dev.sum()

1772296598

In [17]:
#dica: formatar o número da soma
soma = ativos_dev.sum()
print(f'R$ {soma:,.2f}')

R$ 1,772,296,598.00


In [19]:
#encontrar a média do array
ativos_dev.mean()

499.988502934

Compatibilidade entre Arrays
precisam ter pelo menos o mesmo n. de colunas


In [21]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
b = np.array([[10,20,30,40,50]])

print(a.shape, b.shape)

(2, 5) (1, 5)


In [23]:
#é possível realizar operacoes matematicas com arrays compatives, como a soma
a + b

array([[11, 22, 33, 44, 55],
       [16, 27, 38, 49, 60]])

In [25]:
# A soma acumulada
(a + b).cumsum()

array([ 11,  33,  66, 110, 165, 181, 208, 246, 295, 355])

In [28]:
# O produto acumulado
(a + b).cumprod()

array([        11,        242,       7986,     351384,   19326120,
        309217920, -241050752, -569993984, 2135065856, -745067520])

In [30]:
# a variância
(a + b).var()

248.25

In [32]:
# desvio padrão
(a + b).std()

15.75595125658873

In [34]:
#Não compatibilidade entre arrays (3,5) e (3,3)
c = np.array([[0,5,10,15,20], [0,10,20,30,40], [0,100,200,300,400]])
d = np.array([[1,5,10], [2,7,9], [3,4,6]])

print(c.shape, d.shape)

(3, 5) (3, 3)


In [35]:
#não é possível realizar operacoes matematicas com arrays nao compatives, como a subtracao
c -d

ValueError: operands could not be broadcast together with shapes (3,5) (3,3) 

In [36]:
#logo, é possível concluir que arrays (2,1) e (1,2) não são iguais e sequer compatíveis

e = np.array([[8], [16]])
f = np.array([[8,16]])
print(e.shape, f.shape)

(2, 1) (1, 2)


Dimensões de Numpy Array
.flatten()
.reshape()
utilizade em manipular dimensões

In [38]:
# observe o array (5,2)

g = np.array([[1,7], [24,12], [80,33], [57,99], [6,60]])
print(g, g.shape)

[[ 1  7]
 [24 12]
 [80 33]
 [57 99]
 [ 6 60]] (5, 2)


In [40]:
# .flatten() recolhe todos os elementos em apenas uma dimensão

g_flatten = g.flatten()
print(g_flatten, g_flatten.shape)

[ 1  7 24 12 80 33 57 99  6 60] (10,)


In [43]:
# .reshape() atribui nova dimensaop a um array sem modificar seus elementos

g_reshape = g.reshape(2,5)

print(g_reshape, g_reshape.shape)

[[ 1  7 24 12 80]
 [33 57 99  6 60]] (2, 5)


In [45]:
# é util caso se deseje realizar operações matemáticas com arrays incompatíveis

e = np.array([[8], [16]]) # (2,1)
f = np.array([[8,16]]) # (1,2)

# .reshape() em algum dos arrays para os deixar compatíveis ao realizar a multiplicação

In [46]:
# optando pelo reshape no array 'e'
e.reshape(1,2)* f

array([[ 64, 256]])

Geradores Pseudoaleatórios
import random
numpy random

In [48]:
#utilizando o módulo random do python
import random
numeros = [random.gauss(0,1) for _ in range(100)]
print(numeros)

[-0.8153453886326092, -0.6332750325096062, -0.7699873357400113, 0.8702509454038116, 0.5431689399234423, 0.4101728710631007, -1.0018916397388038, 0.42538612090106875, -0.09534171840370262, -0.053542957279878914, 0.4503272415452014, -0.02506447238358911, -0.9385975160709882, 0.3256089533805671, 0.2622498763518953, 0.9956678613185984, 0.3907345842439219, -0.14021157542609602, 0.991148465108516, 1.2074632885872696, -1.1705083043777025, 0.34624826841388817, 3.0634787026158774, 1.2236397444688962, -0.11570155767486834, -0.5036558265797171, 3.2216902546087103, 0.7621083733164096, 0.7313624605616031, -0.08550974539977488, 0.15036835851605743, -0.31577085753160605, 1.1916294471247422, -2.9057086089711825, 0.6703697724953607, 0.8790506304265372, -0.16871066312853938, -0.4519645232756926, 0.04376755377352081, -0.9609976032792837, -1.9491927904918842, 0.8903958905091826, 0.7885130567761166, -0.784036785681631, 0.08314117473719596, 1.412435070239534, -0.7745773450946201, 0.39493901526203906, -0.773

In [50]:
# gere 100 numeros a partir de uma distribuicao normal
numeros = np.random.normal(size=100)

print(numeros)

[-2.17767452  0.73231249 -0.83437482 -2.69261558  0.40849342 -0.15712524
 -1.74419131  0.27001401  0.35142608  0.26226124 -0.01109558  0.42745148
  1.52650143  0.42481801 -1.29113962  1.07566605 -0.68518804  0.63644597
  1.55514501  1.13773748  0.68359393 -0.28891385 -0.33511938 -0.13257996
  0.66185663  0.31531363  0.9819867  -0.34411459  0.34720854  1.00236398
  0.35947322 -0.47258984  1.20099407 -0.22311043 -0.4123384  -1.76348464
  0.10435895  1.20178228  0.90311019 -0.15716119  2.34782355 -1.44193802
  0.48682354 -0.2795165   0.37963174  0.66867925  0.83068039  0.34305244
 -0.72793746 -0.61002005  1.8248921   1.08634608 -1.07314032 -0.0512534
 -1.32861291 -1.43646226 -0.03563809 -0.70897845 -0.42153392  0.10508457
  0.09601397  2.41854572 -0.99814529  0.5314823  -0.6586929  -0.9112358
  0.8592946   0.84200752 -0.55185582 -0.57979064 -1.3786519   0.91248272
 -0.20852471  0.82891191 -1.33464731  0.72884475 -0.18907167  2.80700039
 -1.44915615 -0.09952112  0.10063132 -0.59024115  0.1

In [52]:
#considere a seguinte lista
nomes = ['Ana', 'Gustavo', 'Thais', 'Natalia', 'Julio', 'Max', 'Felipe', 'Alan', 'Paulo', 'Maria', 'Maysa', 'Kevyn']

In [55]:
import random
random.sample(nomes,3)

['Alan', 'Paulo', 'Maria']

In [56]:
#numpy random
#escolher aleatoriamente 3 numeros

np.random.choice(nomes, size = 3)


array(['Max', 'Ana', 'Max'], dtype='<U7')